# Generated by Django 4.2.1 on 2023-06-19 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduit',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categorie',
            name='magasin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produit.magasin'),
        ),
    ]
