# Generated by Django 4.2.1 on 2023-06-19 11:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonne_livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Bulletin_de_commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('state', models.CharField(choices=[('demander', 'Demander'), ('approver', 'Approver'), ('supprimer', 'Supprimer'), ('traiter', 'Traiter')], default='demander', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='type_bl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typpe', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EntreeDeProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_entree', models.IntegerField()),
                ('bl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.bonne_livraison')),
                ('produit_entree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produit.produit')),
            ],
        ),
        migrations.CreateModel(
            name='DemandeDeProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_demande', models.IntegerField()),
                ('quantite_fournie', models.IntegerField(blank=True, null=True)),
                ('date_sortie', models.DateField(default=django.utils.timezone.now)),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.bulletin_de_commande')),
                ('produit_demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produit.produit')),
            ],
        ),
    ]
