# Generated by Django 4.2.1 on 2023-06-19 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('transactions', '0001_initial'),
        ('produit', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin_de_commande',
            name='employe',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='users.employee'),
        ),
        migrations.AddField(
            model_name='bulletin_de_commande',
            name='produits_demandes',
            field=models.ManyToManyField(through='transactions.DemandeDeProduit', to='produit.produit'),
        ),
        migrations.AddField(
            model_name='bonne_livraison',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.fournisseur'),
        ),
        migrations.AddField(
            model_name='bonne_livraison',
            name='produit',
            field=models.ManyToManyField(through='transactions.EntreeDeProduit', to='produit.produit'),
        ),
        migrations.AddField(
            model_name='bonne_livraison',
            name='type_bl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.type_bl'),
        ),
    ]
