# Generated by Django 4.2.1 on 2026-05-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_add_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeapprovisionnement',
            name='etat',
            field=models.CharField(choices=[('created', 'Créée'), ('sent', 'Envoyée'), ('delivered', 'Livrée')], default='created', max_length=20),
        ),
    ]
