# Generated by Django 4.2.1 on 2026-05-09 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_demandeapprovisionnement_etat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandeapprovisionnement',
            name='delai_max_jours',
        ),
        migrations.RemoveField(
            model_name='demandeapprovisionnement',
            name='prix_max',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='delai_livraison_jours',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='prix_reference',
        ),
    ]
